#!/bin/sh

APPID=org.webosinternals.xecutah

APPS=/media/cryptofs/apps

[ -d $APPS ] || { echo "Requires webOS 1.3.5 or later" ; exit 1 ; }

# Remove the saverestore executable
rm -f /var/usr/sbin/${APPID}

# Remove the dbus service
rm -f /var/palm/ls2/services/prv/${APPID}.service /var/palm/ls2/services/pub/${APPID}.service

# Remove the ls2 roles
rm -f /var/palm/ls2/roles/prv/${APPID}.json /var/palm/ls2/roles/pub/${APPID}.json

# Stop the service if running
/sbin/stop ${APPID} || true
/usr/bin/killall -9 ${APPID} || true

# Remove the upstart script
rm -f /var/palm/event.d/${APPID}

exit 0
